{"uuid": "295556db-972a-4419-b88d-c5574c785c2e", "children": ["c56b52f6-3f9f-49fb-81b3-44b09227dde4", "270c7a7a-cc37-4a26-a025-8a4015432f71", "9d7057ec-0ae9-4866-8b72-ee5087069eb5", "64f9c6ef-ece8-4cae-a2a9-df47346aaf5f", "526a1521-5697-4ef4-806f-b20261a3df59", "62bf147c-28d1-4fa9-83ee-0918084dc309"], "befores": [{"name": "driver_setup", "status": "passed", "start": 1709268599116, "stop": 1709268603113}], "afters": [{"name": "driver_setup::0", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=53403): Max retries exceeded with url: /session/8a1eaff826e5545fec33fea42b56e266/window (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1053014d0>: Failed to establish a new connection: [Errno 61] Connection refused'))\n", "trace": "  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/allure_commons/_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/testcases/conftest.py\", line 19, in driver_setup\n    driver.close()\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 458, in close\n    self.execute(Command.CLOSE)\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 345, in execute\n    response = self.command_executor.execute(driver_command, params)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 302, in execute\n    return self._request(command_info[0], url, body=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py\", line 322, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 136, in request\n    return self.request_encode_url(\n           ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/_request_methods.py\", line 183, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/poolmanager.py\", line 444, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 877, in urlopen\n    return self.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 847, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/Users/nishantchauhan/PycharmProjects/QuarkAutomation/.venv/lib/python3.11/site-packages/urllib3/util/retry.py\", line 515, in increment\n    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1709268669856, "stop": 1709268669863}], "start": 1709268599116, "stop": 1709268669863}